# Generated by Django 5.0.4 on 2024-04-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_onetimepassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimepassword',
            old_name='code',
            new_name='otp',
        ),
    ]
