# Generated by Django 5.0.4 on 2024-04-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofermenceevent',
            old_name='challenge_area_id',
            new_name='challenge_event_id',
        ),
    ]
