# Generated by Django 5.0.4 on 2024-04-27 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_challenge_area_id_studentprofermenceevent_challenge_event_id'),
        ('system_admin', '0003_remove_event_faculty_name_facultydepartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='faculty_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.facultydepartment'),
        ),
    ]
