# Generated by Django 5.0.4 on 2024-05-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentprofile_faculty_department'),
        ('system_admin', '0004_alter_area_faculty_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='faculty_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system_admin.facultydepartment'),
        ),
    ]
