# Generated by Django 5.0.4 on 2024-05-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentprofile_faculty_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
    ]
