# Generated by Django 5.0.4 on 2024-05-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_studentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gpa',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
    ]
