# Generated by Django 5.0.4 on 2024-05-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentprofile_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='earned_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
