# Generated by Django 5.0.4 on 2024-05-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofermencearea',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofermenceevent',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
