# Generated by Django 5.0.4 on 2024-05-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_studentprofermencearea_is_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'custom_table_name',
            },
        ),
    ]
