# Generated by Django 5.0.4 on 2024-05-16 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_member', '0011_rename_date_ubdated_challengearea_date_updated_and_more'),
        ('student', '0013_rename_studenstprofile_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofermenceevent',
            name='challenge_event_id',
        ),
        migrations.RemoveField(
            model_name='studentprofermenceevent',
            name='student_profile_id',
        ),
        migrations.CreateModel(
            name='StudentPerformanceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('challenge_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_member.challengearea')),
                ('student_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
            options={
                'db_table': 'student_performance_area',
            },
        ),
        migrations.CreateModel(
            name='StudentPerformanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('challenge_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_member.challengeevent')),
                ('student_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
            options={
                'db_table': 'student_performance_event',
            },
        ),
        migrations.DeleteModel(
            name='StudentProfermenceArea',
        ),
        migrations.DeleteModel(
            name='StudentProfermenceEvent',
        ),
    ]
