# Generated by Django 5.0.4 on 2024-04-26 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParagrapEvent',
            new_name='ParagraphEvent',
        ),
        migrations.CreateModel(
            name='ParagraphArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(max_length=4000)),
                ('example', models.TextField(max_length=4000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('faculty_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_member.facultymemberprofile')),
                ('topic_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_member.topicarea')),
            ],
            options={
                'db_table': 'paragraph_area',
            },
        ),
        migrations.DeleteModel(
            name='ParagrapArea',
        ),
    ]
