# Generated by Django 5.0.4 on 2024-04-27 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_member', '0003_facultymemberprofile_faculty_department'),
        ('system_admin', '0004_alter_area_faculty_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymemberprofile',
            name='faculty_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.facultydepartment'),
        ),
    ]
