# Generated by Django 5.0.4 on 2024-05-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_member', '0004_alter_facultymemberprofile_faculty_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionevent',
            old_name='challenge_area_id',
            new_name='challenge_event_id',
        ),
        migrations.RenameField(
            model_name='topicarea',
            old_name='faculty_member',
            new_name='faculty_member_id',
        ),
        migrations.RenameField(
            model_name='topicevent',
            old_name='faculty_member',
            new_name='faculty_member_id',
        ),
        migrations.RemoveField(
            model_name='challengearea',
            name='faculty_profile_id',
        ),
        migrations.RemoveField(
            model_name='paragrapharea',
            name='faculty_profile_id',
        ),
    ]
