# Generated by Django 5.0.4 on 2024-05-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_member', '0005_rename_challenge_area_id_questionevent_challenge_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeevent',
            name='faculty_profile_id',
        ),
    ]
