# Generated by Django 5.0.4 on 2024-05-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_member', '0009_alter_challengearea_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultymemberprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='facultymemberprofile',
            name='last_name',
        ),
    ]
