# Generated by Django 5.0.4 on 2024-04-26 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_admin_profile',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100)),
                ('faculty_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('date_start', models.DateTimeField(auto_now=True)),
                ('date_end', models.DateTimeField(blank=True)),
                ('admin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.systemadminprofile')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('admin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.systemadminprofile')),
            ],
            options={
                'db_table': 'area',
            },
        ),
    ]
