# Generated by Django 5.0.4 on 2024-04-27 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0003_remove_event_faculty_name_facultydepartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='faculty_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.facultydepartment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='faculty_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.facultydepartment'),
        ),
        migrations.AlterField(
            model_name='facultydepartment',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='facultydepartment',
            name='department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultydepartment',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultydepartment',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
