# Generated by Django 5.0.4 on 2024-05-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0004_alter_area_faculty_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemadminprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='systemadminprofile',
            name='last_name',
        ),
    ]
