# Generated by Django 5.0.4 on 2024-05-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0005_remove_systemadminprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='date_ubdated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_ubdated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='facultydepartment',
            old_name='date_ubdated',
            new_name='date_updated',
        ),
    ]
