# Generated by Django 5.0.4 on 2024-04-25 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty_member_profile',
            },
        ),
        migrations.CreateModel(
            name='ChallengeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('H', 'Hard'), ('E', 'Easy'), ('S', 'Simple')], max_length=10)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('faculty_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_menber.facultymemberprofile')),
            ],
            options={
                'db_table': 'challenge_event',
            },
        ),
        migrations.CreateModel(
            name='ChallengeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('H', 'Hard'), ('E', 'Easy'), ('S', 'Simple')], max_length=10)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('faculty_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_menber.facultymemberprofile')),
            ],
            options={
                'db_table': 'challenge_area',
            },
        ),
        migrations.CreateModel(
            name='QuestionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=500)),
                ('total_points', models.PositiveIntegerField()),
                ('time_value', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('challenge_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_menber.challengearea')),
            ],
            options={
                'db_table': 'question_area',
            },
        ),
        migrations.CreateModel(
            name='OptionsArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_syntax', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('questions_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_menber.questionarea')),
            ],
            options={
                'db_table': 'options_area',
            },
        ),
        migrations.CreateModel(
            name='QuestionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=500)),
                ('total_points', models.PositiveIntegerField()),
                ('time_value', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('challenge_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_menber.challengeevent')),
            ],
            options={
                'db_table': 'question_event',
            },
        ),
        migrations.CreateModel(
            name='OptionsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_syntax', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('questions_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_menber.questionevent')),
            ],
            options={
                'db_table': 'options_event',
            },
        ),
        migrations.CreateModel(
            name='TopicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=2048)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.area')),
                ('faculty_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_menber.facultymemberprofile')),
            ],
            options={
                'db_table': 'topic_area',
            },
        ),
        migrations.CreateModel(
            name='ParagrapArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(max_length=4000)),
                ('example', models.TextField(max_length=4000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('topic_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_menber.topicarea')),
            ],
            options={
                'db_table': 'paragraph_area',
            },
        ),
        migrations.AddField(
            model_name='challengearea',
            name='topic_area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_menber.topicarea'),
        ),
        migrations.CreateModel(
            name='TopicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=2048)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.event')),
                ('faculty_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_menber.facultymemberprofile')),
            ],
            options={
                'db_table': 'topic_event',
            },
        ),
        migrations.CreateModel(
            name='ParagrapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(max_length=4000)),
                ('example', models.TextField(max_length=4000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_ubdated', models.DateField(auto_now=True, null=True)),
                ('topic_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_menber.topicevent')),
            ],
            options={
                'db_table': 'paragraph_event',
            },
        ),
        migrations.AddField(
            model_name='challengeevent',
            name='topic_event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_menber.topicevent'),
        ),
    ]
